# Generated by Django 3.2 on 2021-05-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_attraction', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='tourist_attraction',
            field=models.ManyToManyField(to='tourist_attraction.TouristAttraction'),
        ),
    ]
