# Generated by Django 3.2 on 2021-05-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('core', '0002_touristspot_tourist_attraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='comments',
            field=models.ManyToManyField(to='comments.Comment'),
        ),
    ]
