# Generated by Django 3.2 on 2021-05-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('core', '0003_touristspot_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='assessment',
            field=models.ManyToManyField(to='assessment.Assessment'),
        ),
    ]
