# Generated by Django 3.2 on 2021-05-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20210503_0028'),
        ('core', '0004_touristspot_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='address',
            field=models.ManyToManyField(to='address.Address'),
        ),
    ]
