# Generated by Django 3.2 on 2021-05-03 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20210503_0028'),
        ('core', '0005_touristspot_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='address',
        ),
        migrations.AddField(
            model_name='touristspot',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
            preserve_default=False,
        ),
    ]
