# Generated by Django 3.2 on 2021-05-03 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='line1',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='line2',
            new_name='street',
        ),
    ]
